config/routes.rb
Cloudsearch::Application.routes.draw do
  resources :apis

  get "home/index"

   root :to => "home#index"

end

app/models/api.rb
class Api < ActiveRecord::Base
end

app/controllers/apis_controller.rb
class ApisController < ApplicationController
  # GET /apis
  # GET /apis.xml
  def index
    @apis = Api.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @apis }
    end
  end

  # GET /apis/1
  # GET /apis/1.xml
  def show
    @api = Api.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @api }
    end
  end

  # GET /apis/new
  # GET /apis/new.xml
  def new
    @api = Api.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @api }
    end
  end

  # GET /apis/1/edit
  def edit
    @api = Api.find(params[:id])
  end

  # POST /apis
  # POST /apis.xml
  def create
    @api = Api.new(params[:api])

    respond_to do |format|
      if @api.save
        format.html { redirect_to(@api, :notice => 'Api was successfully created.') }
        format.xml  { render :xml => @api, :status => :created, :location => @api }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @api.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /apis/1
  # PUT /apis/1.xml
  def update
    @api = Api.find(params[:id])

    respond_to do |format|
      if @api.update_attributes(params[:api])
        format.html { redirect_to(@api, :notice => 'Api was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @api.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /apis/1
  # DELETE /apis/1.xml
  def destroy
    @api = Api.find(params[:id])
    @api.destroy

    respond_to do |format|
      format.html { redirect_to(apis_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/apis_helper.rb
module ApisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/apis/_form.html.erb
<%= form_for(@api) do |f| %>
  <% if @api.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api.errors.count, "error") %> prohibited this api from being saved:</h2>

      <ul>
      <% @api.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apis/edit.html.erb
<h1>Editing api</h1>

<%= render 'form' %>

<%= link_to 'Show', @api %> |
<%= link_to 'Back', apis_path %>

app/views/apis/index.html.erb
<h1>Listing apis</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apis.each do |api| %>
  <tr>
    <td><%= api.name %></td>
    <td><%= link_to 'Show', api %></td>
    <td><%= link_to 'Edit', edit_api_path(api) %></td>
    <td><%= link_to 'Destroy', api, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Api', new_api_path %>

app/views/apis/new.html.erb
<h1>New api</h1>

<%= render 'form' %>

<%= link_to 'Back', apis_path %>

app/views/apis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @api.name %>
</p>


<%= link_to 'Edit', edit_api_path(@api) %> |
<%= link_to 'Back', apis_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudSearch</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body style="background: #EEEEEE;">
 
<%= yield %>
 
</body>
</html>